GET http://localhost:3000/api


###

GET http://localhost:3000/api/slides



###

GET http://localhost:3000/api/slide/1



###

PUT http://localhost:3000/api/slide



###

POST http://localhost:3000/api/slide/7

{
    "ID": 6,
    "Data": "{\"test\":12}"
}
